server:
  port: 9296

spring:
  application:
    name: CONFIG-SEVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sad-sadie/config-server/
          clone-on-start: true